### ISSUE TITLE
Can I use this as a drop-in-replacement of https://github.com/easylogic/codemirror-colorpicker?

### ISSUE THREAD

**Issue by lqez** [easylogic/colorpicker#1]
I've used https://github.com/easylogic/codemirror-colorpicker but I'd like to use it without CodeMirror dependency. It looks like this package had been forked from the original one. 

So, can I use this as a drop-in-replacement of https://github.com/easylogic/codemirror-colorpicker?

**Comment by easylogic** [comment]
@lqez  

Yes.

This library is like  codemirror-colorpicker without codemirror dependency.
