### ISSUE TITLE
MacOS 환경에서 node-sass 인스톨 문제

### ISSUE THREAD

**Issue by redgoose-dev** [easylogic/colorpicker#15]
- MacOS: 11.4
- node: 16.3.0
- npm: 7.15.1

MacOS에서 `gyp ERR`련 오류로 `npm install`이 안되는 현상을 겪게 되었습니다.

----

다음과 같은 방식으로 인스톨과 개발화면까지 여는데 성공했습니다.

1. `package.json`의 디펜더시 항목에서 `"rollup-plugin-scss": "^0.4.0",` 삭제합니다. (인스톨시 오류가 나서 막히기 때문에 코드로 삭제합니다.)
2. `npm install`로 인스톨은 성공합니다.
3. `npm install -d node-sass`를 실행하여 최신버전으로 패키지 추가합니다.
4. `npm run dev` 실행하여 개발화면을 확인합니다.

이쯤으로 빌드까지 되는걸 확인했습니다.  
비슷한 상황을 겪는분이 있을까봐 작성해둡니다.

**Comment by easylogic** [comment]
잘 기억하도록 하겠습니다. ^^

**Comment by redgoose-dev** [comment]
일단 닫아두겠습니다. :)
