### ISSUE TITLE
Gradient Picker: how to remove a color stop?

### ISSUE THREAD

**Issue by nzbin** [easylogic/colorpicker#32]

**Comment by easylogic** [comment]
hi @nzbin  

i will implement to remove color stop.

**Comment by easylogic** [comment]
@nzbin 

you can delete color step when click with alt key event fired.

However, we plan to add a delete button to make it visible. I'll release it and let you know

**Comment by easylogic** [comment]
I released new version (v1.10.7)  with bug fix. 

Please test it .  (npm install @easylogic/colorpicker@1.10.7).
