### ISSUE TITLE
Add/Remove colorstops

### ISSUE THREAD

**Issue by Taldorr** [easylogic/colorpicker#33]
I'm using this package in Angular and it does work for the most part. However adding/removing colorstops does not work (Version 1.10.5)

Adding a colorstop on the very left does work, however it seems to be quite buggy.
![image](https://user-images.githubusercontent.com/17960740/141768409-e048ff66-1980-4fe6-af67-403d4f705d39.png)

 Adding one in between to existing stops will throw an error:
![image](https://user-images.githubusercontent.com/17960740/141768489-85f31c9c-9a7d-473a-9d6b-147acb300023.png)
![image](https://user-images.githubusercontent.com/17960740/141768549-9fe18825-95e1-49fa-b0d4-07e6df90377d.png)

Nonetheless, thanks for your great work!

**Comment by easylogic** [comment]
hi @Taldorr 

Sorry for the very late reply.

I'll check again and let you know.

**Comment by easylogic** [comment]
@Taldorr  

you can delete color step when click with alt key event fired. 

However, we plan to add a delete button to make it visible. I'll release it and let you know

**Comment by easylogic** [comment]
@Taldorr  

I released new version (v1.10.7)  with bug fix. 

Please test it .  (npm install @easylogic/colorpicker@1.10.7).
