### ISSUE TITLE
Wrong color after three clicks

### ISSUE THREAD

**Issue by R2-D1** [easylogic/colorpicker#35]
**Describe the bug**
Gradient color picker - After third click in the same place on color steps - one of color #NaNNaNNaN and all gradient is broken after that.

**To Reproduce**
1. Click on color step panel three times in the same place
2. Look at gradient string `linear-gradient(90deg, white 0%, #NaNNaNNaN 46.330275229357795%,#898989 46.330275229357795% 46.330275229357795%,black 100%)`

**Expected behavior**
Gradient has plus three selected steps

**Screenshots**
<img width="760" alt="Screenshot 2022-01-18 at 23 22 59" src="https://user-images.githubusercontent.com/46542768/150020970-2f5032ed-392a-414e-b89c-aa1ac20c5609.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 97.0.4692.71

**Additional context**
Firstly i found this error in [npm package ](https://www.npmjs.com/package/@easylogic/colorpicker), I installed it in my angular application and this error reproduce even after second click. Then i tried to install development application, and there was error after third click. Also I noticed that npm package and develop version has different UI, is it ok? especially I can't see  "Offset connected " checkbox in development app, only text. Also weird that I can't reproduce error on demo [site](https://colorpicker.easylogic.studio/#colorpicker-for-standalone)

**Comment by R2-D1** [comment]
I need help( Please, can you check this bug?

**Comment by Dmitrii-Dudnyk** [comment]
Have the same issue

**Comment by easylogic** [comment]
@R2-D1  @Dmitrii-Dudnyk  

I released v1.10.10

Please test it.
