### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by lqez** [easylogic/colorpicker#4]
**Describe the bug**
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.` was printed a lot from `colorpicker.js`.

**To Reproduce**
Turn on `verbose` on the browser console and see warnings.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-09-10 at 6 36 30 PM" src="https://user-images.githubusercontent.com/579366/64602537-f0b19c80-d3f9-11e9-9a6a-13fc57487439.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 
 - Version: 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
XRef: https://www.chromestatus.com/feature/5745543795965952
XRef: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners?hl=ko

**Comment by easylogic** [comment]
i fixed at v1.9.64
