### ISSUE TITLE
다크테마버전 출시요망

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/colorpicker#8]
다크ui에 어울리게 생성시 다크버전을 설정할 수 있는 옵션 추가 요망

**Comment by easylogic** [comment]
살짝 적용 해봐야겠네요. 여기도.

**Comment by redgoose-dev** [comment]
다크모드를 그저 적용만 하면 다크모드를 원하지도 않는데도 적용이 될겁니다.
그래서 옵션을 둬서 다크모드를 사용할것인지에 대한 여부를 알 수 있도록 옵션을 두고 다크모드를 사용한다면 스타일이 변할 수 있도록 조취가 필요할 것입니다.

```
<div class="">
```

아마도 이런 모습이 되지 않을까 예상됩니다.

**Comment by redgoose-dev** [comment]
다크모드는 고민하다가 내린 결론은 컴포넌트에서 다크모드 사용여부를 정하는것보다 제품이나 서비스를 만드는 외부에서 해결해야하는 부분인게 맞다고 생각합니다.
스타일시트를 최대한 고칠 수 있도록 스타일을 열어뒀으니 참고하시면 얼추 고칠 수 있을겁니다.

스타일시트 문서: https://github.com/easylogic/colorpicker/tree/main/src/scss
