### ISSUE TITLE
닫기기능 추가

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/colorpicker#9]
ui상 닫기가 없음.

**Comment by easylogic** [comment]
원래 컬러 피커 오픈하고 닫을 때는 자동으로 다른쪽 누르면 닫히게 되어 있는데요. 
선기님쪽 에디터에서는 구조화된 inline 형태의 피커를 사용하기 때문에 닫기를 선기님쪽에서 해줘야 합니다. 두둥
